version: '3.7'

services:
  web:
    build: .
    command: >
      bash -c "alembic upgrade head
      && gunicorn main:api -b :8080 -k gevent --reload"
    volumes:
      - ./app:/usr/src/app/app
    ports:
      - 8000:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: rehabApp
    ports:
    - 5432:5432
volumes:
  postgres_data: