version: '3.7'

services:
  web:
    build: .
    command: >
      bash -c "cd app
      && gunicorn main:api -b :8080 --reload"
    volumes:
      - ./app:/usr/src/app/app
    ports:
      - 8000:8080