"""Create areas table

Revision ID: 086e20e849e3
Revises: 2eb9c6cfe0b4
Create Date: 2020-05-08 17:00:12.800266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086e20e849e3'
down_revision = '2eb9c6cfe0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('areas')
    # ### end Alembic commands ###
