"""Add color and prepend to questions table

Revision ID: 0a8bc7e1499d
Revises: 9a110ba78a87
Create Date: 2020-05-08 17:02:27.325460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8bc7e1499d'
down_revision = '9a110ba78a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('color_id', sa.Integer(), nullable=False))
    op.add_column('questions', sa.Column('prepend_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'prepends', ['prepend_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'colors', ['color_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'prepend_id')
    op.drop_column('questions', 'color_id')
    # ### end Alembic commands ###
