"""Create table tress + update structure of other tables

Revision ID: 0d16ffe09f90
Revises: 99c858a5d1f8
Create Date: 2020-05-25 16:02:48.477089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d16ffe09f90'
down_revision = '99c858a5d1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('area_details')
    op.add_column('areas', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('areas', sa.Column('tree_id', sa.Integer(), nullable=False))
    op.add_column('areas', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('areas', sa.Column('x', sa.Float(), nullable=True))
    op.add_column('areas', sa.Column('y', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'areas', 'trees', ['tree_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('areas', 'text')
    op.drop_column('areas', 'tree')
    op.add_column('options', sa.Column('side', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('tree_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'questions', 'trees', ['tree_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'tree_id')
    op.drop_column('options', 'side')
    op.add_column('areas', sa.Column('tree', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('areas', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'y')
    op.drop_column('areas', 'x')
    op.drop_column('areas', 'width')
    op.drop_column('areas', 'tree_id')
    op.drop_column('areas', 'height')
    op.create_table('area_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('x', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('y', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('width', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('height', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name='area_details_area_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='area_details_pkey')
    )
    op.drop_table('trees')
    # ### end Alembic commands ###
