"""Add column label to options table

Revision ID: 121d3f923987
Revises: d1f37ec5225a
Create Date: 2020-05-19 23:01:29.339778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121d3f923987'
down_revision = 'd1f37ec5225a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'label')
    # ### end Alembic commands ###
