"""Change password type users table

Revision ID: 1d50461fde35
Revises: fe8fc7f82c75
Create Date: 2020-04-25 23:17:47.376734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d50461fde35'
down_revision = 'fe8fc7f82c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('users', sa.Column('password', sa.Binary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
