"""Create table questions

Revision ID: 273b41375aae
Revises: d1e82a1cda44
Create Date: 2020-04-24 13:37:31.422608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273b41375aae'
down_revision = 'd1e82a1cda44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    
    # ### end Alembic commands ###
