"""Added surname authors table

Revision ID: 289d15faed2e
Revises: 491aaab00408
Create Date: 2020-04-10 22:36:46.033430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289d15faed2e'
down_revision = '491aaab00408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('surname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'surname')
    # ### end Alembic commands ###
