"""Create user_backlogs table

Revision ID: 33d53df86f94
Revises: ffddf88aecba
Create Date: 2020-06-29 20:52:16.726579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d53df86f94'
down_revision = 'ffddf88aecba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_backlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_diagnose_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_diagnose_id'], ['user_diagnoses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_backlogs')
    # ### end Alembic commands ###
