"""Create subarea_diagnoses table

Revision ID: 4665028487a6
Revises: 630355d9df37
Create Date: 2020-05-08 17:07:33.733951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4665028487a6'
down_revision = '630355d9df37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subarea_diagnoses',
    sa.Column('subarea_id', sa.Integer(), nullable=True),
    sa.Column('diagnose_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diagnose_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subarea_id'], ['options.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subarea_diagnoses')
    # ### end Alembic commands ###
