"""Change author name to author_id

Revision ID: 491aaab00408
Revises: 82fbd6f2a6db
Create Date: 2020-04-01 16:27:00.341869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491aaab00408'
down_revision = '82fbd6f2a6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quotes', 'authors', ['author_id'], ['id'])
    op.drop_column('quotes', 'author_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'author_id')
    # ### end Alembic commands ###
