"""Drop user_diagnoses table

Revision ID: 4afa564d7d15
Revises: 7db499e582e1
Create Date: 2020-05-08 17:22:22.167990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afa564d7d15'
down_revision = '7db499e582e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_diagnoses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_diagnoses',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diagnose_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diagnose_id'], ['diagnoses.id'], name='user_diagnoses_diagnose_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], name='user_diagnoses_sequence_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_diagnoses_user_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
