"""Add atributes to diagnoses table

Revision ID: 52fb727f3eca
Revises: a6ab9b57f3de
Create Date: 2020-06-16 15:20:37.590367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52fb727f3eca'
down_revision = 'a6ab9b57f3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('cause', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('cure', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('definition', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('diagnostic', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('prevention', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('svk', sa.String(), nullable=True))
    op.add_column('diagnoses', sa.Column('symptoms', sa.Text(), nullable=True))
    op.drop_column('diagnoses', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('diagnoses', 'symptoms')
    op.drop_column('diagnoses', 'svk')
    op.drop_column('diagnoses', 'prevention')
    op.drop_column('diagnoses', 'diagnostic')
    op.drop_column('diagnoses', 'definition')
    op.drop_column('diagnoses', 'cure')
    op.drop_column('diagnoses', 'cause')
    # ### end Alembic commands ###
