"""Create sequences table

Revision ID: 630355d9df37
Revises: ed7bf5b12a8c
Create Date: 2020-05-08 17:05:56.431530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630355d9df37'
down_revision = 'ed7bf5b12a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['next_id'], ['sequences.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequences')
    # ### end Alembic commands ###
