"""Create table area_details

Revision ID: 8804ebf2ff21
Revises: 695260d09eb3
Create Date: 2020-05-19 22:56:07.240621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8804ebf2ff21'
down_revision = '695260d09eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('areas', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'text')
    op.drop_table('area_details')
    # ### end Alembic commands ###
