"""Change users table

Revision ID: 8ef81373f869
Revises: 86925ae80176
Create Date: 2020-06-25 22:15:34.245814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef81373f869'
down_revision = '86925ae80176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', nullable=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('google', sa.Boolean(), nullable=True))
    op.drop_column('users', 'refresh_token')
    op.create_check_constraint('at-least-one', 'users', 'password IS NOT NULL OR google IS TRUE'),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', nullable=False)
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'google')
    op.drop_column('users', 'email_verified')
    op.drop_constraint(name='at-least-one')
    # ### end Alembic commands ###
