"""Add nullable to area_id in area_details table

Revision ID: 99c858a5d1f8
Revises: a6e61a0d7623
Create Date: 2020-05-21 13:30:25.028937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c858a5d1f8'
down_revision = 'a6e61a0d7623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('area_details', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('area_details', 'area_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
