"""change author to author name quotes table

Revision ID: a481d5fbb0be
Revises: dce79acea57a
Create Date: 2020-03-25 08:40:13.279772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a481d5fbb0be'
down_revision = 'dce79acea57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('author_name', sa.String(), nullable=True))
    op.drop_column('quotes', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('author', sa.VARCHAR(), nullable=True))
    op.drop_column('quotes', 'author_name')
    # ### end Alembic commands ###
