"""Delete table subarea_diagnoses

Revision ID: a6ab9b57f3de
Revises: ad9311d8c68a
Create Date: 2020-05-26 19:33:03.730376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ab9b57f3de'
down_revision = 'ad9311d8c68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subarea_diagnoses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subarea_diagnoses',
    sa.Column('subarea_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diagnose_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diagnose_id'], ['diagnoses.id'], name='subarea_diagnoses_diagnose_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subarea_id'], ['options.id'], name='subarea_diagnoses_subarea_id_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
