"""Add column tree to areas table

Revision ID: a6e61a0d7623
Revises: e28918424b7f
Create Date: 2020-05-20 00:58:26.994583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e61a0d7623'
down_revision = 'e28918424b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('tree', sa.String(), nullable=True))
    op.drop_column('areas', 'back_name')
    op.drop_column('areas', 'front_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('front_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('areas', sa.Column('back_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('areas', 'tree')
    # ### end Alembic commands ###
