"""Create tree_references table

Revision ID: ad9311d8c68a
Revises: 0d16ffe09f90
Create Date: 2020-05-26 11:46:09.977620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9311d8c68a'
down_revision = '0d16ffe09f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tree_references',
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('ref_tree_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ref_tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tree_references')
    # ### end Alembic commands ###
