"""UserDiagnoses table on delete cascade

Revision ID: b4a0653caa88
Revises: fc9e31eb5d7c
Create Date: 2020-04-29 21:23:18.697282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a0653caa88'
down_revision = 'fc9e31eb5d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_diagnoses_user_id_fkey', 'user_diagnoses', type_='foreignkey')
    op.drop_constraint('user_diagnoses_diagnose_id_fkey', 'user_diagnoses', type_='foreignkey')
    op.create_foreign_key(None, 'user_diagnoses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_diagnoses', 'diagnoses', ['diagnose_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_diagnoses', type_='foreignkey')
    op.drop_constraint(None, 'user_diagnoses', type_='foreignkey')
    op.create_foreign_key('user_diagnoses_diagnose_id_fkey', 'user_diagnoses', 'diagnoses', ['diagnose_id'], ['id'])
    op.create_foreign_key('user_diagnoses_user_id_fkey', 'user_diagnoses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
