"""Rename label to text in options table

Revision ID: d1f37ec5225a
Revises: 8804ebf2ff21
Create Date: 2020-05-19 23:00:20.009535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f37ec5225a'
down_revision = '8804ebf2ff21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('text', sa.String(), nullable=True))
    op.drop_column('options', 'label')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('options', 'text')
    # ### end Alembic commands ###
