"""Change verified to verification token + added password reset

Revision ID: d72424d9a7a8
Revises: f9134860bffa
Create Date: 2020-06-26 12:34:54.240669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72424d9a7a8'
down_revision = 'f9134860bffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'password_reset')
    # ### end Alembic commands ###
