"""Add column name to areas table

Revision ID: e28918424b7f
Revises: a004515a4c29
Create Date: 2020-05-20 00:46:00.236283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e28918424b7f'
down_revision = 'a004515a4c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('areas', 'name')
    # ### end Alembic commands ###
