"""Create options table

Revision ID: ed7bf5b12a8c
Revises: 0a8bc7e1499d
Create Date: 2020-05-08 17:03:48.047126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7bf5b12a8c'
down_revision = '0a8bc7e1499d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('next_question_id', sa.Integer(), nullable=True),
    sa.Column('next_diagnose_id', sa.Integer(), nullable=True),
    sa.Column('next_area_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(next_question_id IS NOT NULL AND next_diagnose_id IS NULL AND next_area_id IS NULL)OR (next_question_id IS NULL AND next_diagnose_id IS NOT NULL AND next_area_id IS NULL)OR (next_question_id IS NULL AND next_diagnose_id IS NULL AND next_area_id IS NOT NULL)', name='one-of-three'),
    sa.CheckConstraint('(question_id IS NOT NULL AND area_id IS NULL)OR (question_id IS NULL AND area_id IS NOT NULL)', name='one-of-two'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_area_id'], ['areas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_diagnose_id'], ['diagnoses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    # ### end Alembic commands ###
