"""Create table options

Revision ID: faefd2b45638
Revises: 273b41375aae
Create Date: 2020-04-24 13:38:01.778953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faefd2b45638'
down_revision = '273b41375aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('next_diagnose_id', sa.Integer(), nullable=True),
    sa.Column('next_question_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(next_question_id IS NULL AND next_diagnose_id IS NOT NULL)OR (next_question_id IS NOT NULL AND next_diagnose_id IS NULL)', name='one-of-two'),
    sa.ForeignKeyConstraint(['next_diagnose_id'], ['diagnoses.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    # ### end Alembic commands ###
