"""Change column types for password and rename token_created_at to refresh_token

Revision ID: fc9e31eb5d7c
Revises: 6bf60f5ce212
Create Date: 2020-04-29 20:19:41.011085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc9e31eb5d7c'
down_revision = '6bf60f5ce212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'token_created_at')
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'password')
    op.add_column('users', sa.Column('token_created_at', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
