"""Add start_date to user_diagnoses table

Revision ID: ffddf88aecba
Revises: 78d872a62890
Create Date: 2020-06-29 20:51:14.704655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffddf88aecba'
down_revision = '78d872a62890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_diagnoses', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_diagnoses', 'start_date')
    # ### end Alembic commands ###
